
project_id = "qkrmrlecuolwnayxbqbm"

[functions.extract-metadata]
verify_jwt = true

[functions.summarize-content]
verify_jwt = true

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[realtime]
enabled = true

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Apply database schema migration
[inbucket]
enabled = false

# Apply database schema migration
[[migrations]]
version = "20250515_api_keys_management"
