// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qkrmrlecuolwnayxbqbm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFrcm1ybGVjdW9sd25heXhicWJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDcyMTI0NjQsImV4cCI6MjA2Mjc4ODQ2NH0.6bzbTWETTl2iyv7qLHCzPTZzBEdaYw_8PT04bkMEu3E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);